/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package listInterface;

import java.util.*;

public class ListInterfaceDemo {
  
    public static void main(String[] args) {
        List a1 = new ArrayList();
        a1.add("Zoro");
        a1.add("Zora");
        a1.add("Zara");
        System.out.println("ArrayList Elements");
        System.out.println("\t" + a1);

        List l1 = new LinkedList();
        l1.add("Zara");
        l1.add("Mahnaz");
        l1.add("Ayan");
        System.out.println();
        System.out.println("LinkedList Elements");
        System.out.println("\t" + l1);
    }
}
