/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ioWalkthrough;
import java.io.*;
import java.io.BufferedReader;
import java.io.IOException;

import fj.Unit;
import fj.data.$;
import fj.data.IO;
import fj.data.IOFunctions;
import fj.data.IOW;
import fj.data.SafeIO;
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.Closeable;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.Charset;
import java.util.Arrays;


public class IoWalkthrough {
    
    public static void main(String[] args) {
        final IO<Unit> askName = () -> {
            System.out.println("Hi what's your name?");
            return Unit.unit();
        };
        
        IO<Unit> askAndPromptName = IOFunctions.append(askName, promptName);

        final IO<String> readName = () -> new BufferedReader(new InputStreamReader(System.in).readLine());

        final IO<Unit> program = IOFunctions.bind(askAndPromptName, ignored -> readAndPrintUpperCasedName);

        toSafeValidation(program).run().on((IOException e) -> {e.printStackTrace(); return Unit.unit(); });

        IOW.lift(stdoutPrintln("what's your name again?")).append(stdout("Name: ")).append(stdinReadLine()).bind(F1W.lift((String s) -> s.toUpperCase()).andThen(IOFunctions::stdoutPrintln)).safe().run().on((IOException e) -> {e.printStackTrace(); return Unit.unit(); });
    
    }
}
