/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junitRules;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class RuleExpectedTest {

    @Rule
      
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
