/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package functionalInterface;

public class FunctionalInterface {
    public static void main(String[] args) {
        System.out.println(MyInterface(run("Test functional interface")));
    }
}

public interface MyInterface {
    public void run();

    public default void doIt() {
        System.out.println("doing it");
    }

    public static void doItStatistically() {
        System.out.println("do it statistically");
    }
}
