/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parameterizedTest;
import org.junit.*;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;

public class MyClass {
    public static void main(String[] args) {
        JUnitCore junit = new JUnitCore();
        junit.addListener(new TextListener(System.out));
        junit.run(MyClass.class);
    }
}


