/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pureFunctions;

public class PureFunction {

    public int sum(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        
    }
}
