/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayExist;

import fj.data.Array;
import static fj.data.Array.array;
import static fj.data.List.fromString;
import static fj.function.Characters.isLowerCase;

public final class ArrayExist {

    public static void main(final String[] args) {
        final Array<String> a = array("Hello", "There", "what", "DAY","iS", "iT");
        final boolean b = a.exists(s -> fromString(s).forall(isLowerCase));
        System.out.println(b);
    }
}
