/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package optionFilter;
import fj.F;
import fj.data.Option;
import static fj.Show.intShow;
import static fj.Show.optionShow;
import static fj.data.Option.none;
import static fj.data.Option.some;
import static fj.function.Integers.even;

public final class OptionFilter {
    public static void main(final String[] args) {
        final Option<Integer> o1 = some(7);
        final Option<Integer> o2 = none();
        final Option<Integer> o3 = some(8);

        final Option<Integer> o4 = o1.filter(even);
        final Option<Integer> o5 = o2.filter(even);
        final Option<Integer> o6 = o3.filter(even);

        F<Integer, Boolean> f = j -> j % 2 == 0;
        final Option<Integer> o7 = o1.filter(f);
        final Option<Integer> o8 = o2.filter(f);
        final Option<Integer> o9 = o3.filter(i -> i % 2 == 0);

        optionShow(intShow).println(o4);
        optionShow(intShow).println(o5);
        optionShow(intShow).println(o6);
    }
}
