/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package singletonPattern;

import singletonPattern.SingleObject;

public class SinglePatternDemo {
 
    public static void main(String[] args) {
        SingleObject object = SingleObject.getInstance();
        object.showMessage();
    }
}
